# Generated by Django 4.2.4 on 2026-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_manager', '0002_liability_investments_account_investment_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
    ]
