# Generated by Django 4.2.4 on 2026-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_manager', '0004_transaction_remove_liability_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('loan', 'Loan')], db_index=True, max_length=12),
        ),
    ]
