from django.urls import path

from .api_views import (
    AccountDetailAPIView,
    AccountListCreateAPIView,
    BudgetDetailAPIView,
    BudgetListCreateAPIView,
    CategoryListAPIView,
    DashboardAPIView,
    ExpenseDetailAPIView,
    ExpenseListCreateAPIView,
    FCMDeviceAPIView,
    IncomeDetailAPIView,
    IncomeListCreateAPIView,
    LoginAPIView,
    LoanListCreateAPIView,
    MeAPIView,
    ProfileAPIView,
    ReceiptUploadAPIView,
    ReportMonthlyAPIView,
    ReportTrendsAPIView,
    RefreshTokenAPIView,
    RegisterAPIView,
    SMSParseAPIView,
    SyncAPIView,
    VerifyTokenAPIView,
)

urlpatterns = [
    path('auth/register/', RegisterAPIView.as_view(), name='api-register'),
    path('auth/login/', LoginAPIView.as_view(), name='api-login'),
    path('auth/refresh/', RefreshTokenAPIView.as_view(), name='api-refresh'),
    path('auth/verify/', VerifyTokenAPIView.as_view(), name='api-verify'),
    path('auth/me/', MeAPIView.as_view(), name='api-me'),
    path('auth/profile/', ProfileAPIView.as_view(), name='api-profile'),
    path('accounts/', AccountListCreateAPIView.as_view(), name='api-account'),
    path('accounts/<int:pk>/', AccountDetailAPIView.as_view(), name='api-account-detail'),
    path('categories/', CategoryListAPIView.as_view(), name='api-categories'),
    path('expenses/', ExpenseListCreateAPIView.as_view(), name='api-expenses'),
    path('expenses/<int:pk>/', ExpenseDetailAPIView.as_view(), name='api-expense-detail'),
    path('income/', IncomeListCreateAPIView.as_view(), name='api-income'),
    path('income/<int:pk>/', IncomeDetailAPIView.as_view(), name='api-income-detail'),
    path('loans/', LoanListCreateAPIView.as_view(), name='api-loans'),
    path('budgets/', BudgetListCreateAPIView.as_view(), name='api-budgets'),
    path('budgets/<int:pk>/', BudgetDetailAPIView.as_view(), name='api-budget-detail'),
    path('reports/monthly/', ReportMonthlyAPIView.as_view(), name='api-report-monthly'),
    path('reports/trends/', ReportTrendsAPIView.as_view(), name='api-report-trends'),
    path('dashboard/', DashboardAPIView.as_view(), name='api-dashboard'),
    path('sync/', SyncAPIView.as_view(), name='api-sync'),
    path('receipts/', ReceiptUploadAPIView.as_view(), name='api-receipts'),
    path('fcm/register/', FCMDeviceAPIView.as_view(), name='api-fcm-register'),
    path('sms/parse/', SMSParseAPIView.as_view(), name='api-sms-parse'),
]
